// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pruning.sql

package db

import (
	"context"
)

const residualUnclassifiedTitles = `-- name: ResidualUnclassifiedTitles :many

SELECT
    lower(btrim(title))                AS title,
    count(*)                           AS jobs,
    array_agg(DISTINCT source)::text[] AS sources
FROM jobs
WHERE closed_at IS NULL
  AND duplicate_of IS NULL
  AND is_tech IS NULL
GROUP BY 1
ORDER BY 2 DESC, 1
LIMIT $1
`

type ResidualUnclassifiedTitlesRow struct {
	Title   string   `json:"title"`
	Jobs    int64    `json:"jobs"`
	Sources []string `json:"sources"`
}

// Catalogue pruning: the queries that find, and eventually remove, jobs that do not
// belong on an IT job board. See the catalog-pruning capability spec.
// The residual unclassified mass grouped into clusters an operator can act on: the
// most frequent titles among live jobs carrying no is_tech signal. Titles are
// normalized (lowercased, trimmed) so one role spelled inconsistently across boards
// reads as one cluster rather than several singletons. Closed and duplicate rows are
// excluded — only a live, canonical posting is worth a dictionary term.
func (q *Queries) ResidualUnclassifiedTitles(ctx context.Context, rowLimit int32) ([]ResidualUnclassifiedTitlesRow, error) {
	rows, err := q.db.Query(ctx, residualUnclassifiedTitles, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResidualUnclassifiedTitlesRow{}
	for rows.Next() {
		var i ResidualUnclassifiedTitlesRow
		if err := rows.Scan(&i.Title, &i.Jobs, &i.Sources); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
